# Generated by Django 5.0.3 on 2024-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_category', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Health', 'Health')], max_length=100)),
            ],
        ),
    ]
